---
- name: Install pip
  apt: pkg=python-pip state=installed
  become: yes
  become_method: sudo

- name: Update pip
  pip: name=pip state=latest

- name: Install virtualenv, virtualenvwrapper
  pip: name={{item}} state=present
  with_items:
    - virtualenv
    - virtualenvwrapper
  become: yes
  become_method: sudo

- name: Create virtualenvs
  file: path=/home/vagrant/.virtualenvs state=directory

- name: Set postactivate
  template: src=files/postactivate dest=/home/vagrant/.virtualenvs/postactivate