---
- name: Install Python Django Dev invironment
  hosts: all
  # remote_user: vagrant
  # become: yes
  # become_method: sudo
  user: ubuntu
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get update
    - raw: sudo apt-get -y install python-minimal
  vars:
    zsh_theme: robbyrussell
  roles:
    - common
    - mysql
    - python
    - postgres
