---
- name: Install Django Development Environment
  hosts: all
  user: vagrant
  gather_facts: no
  vars:
    zsh_theme: cloud
  roles:
    - common
    - python
    - mysql
    # - postgres
    # - elasticsearch
